param(
    [string]$Version = "1.3.0"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Output = Join-Path $Root "build.luau"

$Files = Get-ChildItem -Path $Root -Recurse -File -Filter "*.luau" |
    Where-Object {
        $_.FullName -ne $Output -and
        $_.FullName -notmatch "[\\/]\.git[\\/]" -and
        $_.FullName -notmatch "[\\/]vendor[\\/]"
    } |
    Sort-Object { $_.FullName.Substring($Root.Length + 1).Replace("\\", "/") }

$Rows = New-Object System.Collections.Generic.List[object]
$FingerprintBuilder = New-Object System.Text.StringBuilder

foreach ($File in $Files) {
    $Relative = $File.FullName.Substring($Root.Length + 1).Replace("\\", "/")
    $Hash = (Get-FileHash -LiteralPath $File.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    $Rows.Add([pscustomobject]@{ Path = $Relative; Hash = $Hash })
    [void]$FingerprintBuilder.Append($Relative).Append([char]0).Append($Hash).Append("`n")
}

$Sha = [System.Security.Cryptography.SHA256]::Create()
try {
    $Bytes = [System.Text.Encoding]::UTF8.GetBytes($FingerprintBuilder.ToString())
    $Revision = ([System.BitConverter]::ToString($Sha.ComputeHash($Bytes))).Replace("-", "").ToLowerInvariant()
} finally {
    $Sha.Dispose()
}

if (Test-Path -LiteralPath $Output) {
    $Existing = Get-Content -LiteralPath $Output -Raw
    if ($Existing -match 'revision\s*=\s*"([^\"]+)"' -and $Matches[1] -eq $Revision -and
        $Existing -match 'version\s*=\s*"([^\"]+)"' -and $Matches[1] -eq $Version) {
        Write-Host "[build] Manifest already current: $($Revision.Substring(0, 12))"
        exit 0
    }
}

$Generated = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ")
$Lines = New-Object System.Collections.Generic.List[string]
$Lines.Add("-- xanhub-build | generated by tools/update-build.ps1")
$Lines.Add("return {")
$Lines.Add("`tname = `"xanhub-build`",")
$Lines.Add("`tversion = `"$Version`",")
$Lines.Add("`tchannel = `"main`",")
$Lines.Add("`trevision = `"$Revision`",")
$Lines.Add("`tgeneratedAtUTC = `"$Generated`",")
$Lines.Add("`tfileCount = $($Rows.Count),")
$Lines.Add("`tfiles = {")
foreach ($Row in $Rows) {
    $Escaped = $Row.Path.Replace("\\", "\\\\").Replace('"', '\"')
    $Lines.Add("`t`t[`"$Escaped`"] = `"$($Row.Hash)`",")
}
$Lines.Add("`t},")
$Lines.Add("}")

[System.IO.File]::WriteAllText($Output, ($Lines -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))
Write-Host "[build] Wrote build.luau: $($Revision.Substring(0, 12)) ($($Rows.Count) files)"
